version: '2'
services:
  fail2ban:
    image: fail2ban:latest
    #image: universityinnsbruck/fail2ban:latest
    container_name: fail2ban
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./jail.d:/etc/fail2ban/jail.d
      - ./filter.d:/etc/fail2ban/filter.d
      #mount some log volumes here
      - ./log/guacamole:/var/log/tomcat

